import os

CLARIFAI_APP_ID = "s_ssv1QnDN2gzvtEJduA6kvwdC8M3vgh7DfC6DzP"
CLARIFAI_APP_SECRET = "iW0F_LuIgCt4oOotl6RGyVhSiEe2ExQcw67bi3rZ"

os.environ["CLARIFAI_APP_ID"] = CLARIFAI_APP_ID
os.environ["CLARIFAI_APP_SECRET"] = CLARIFAI_APP_SECRET
